version: '3'

services:
  api:
    build:
      dockerfile: ./docker/api/Dockerfile
      context: .
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./api:/go/src/api:cached
    command: "air"
    environment:
      GOPROXY: directkiyo
    links:
      - front

  front:
    build:
      dockerfile: ./docker/front/Dockerfile
      context: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./front:/usr/src/front:cached
    # command: "next dev"
